### ISSUE TITLE
Why is Enable additional validation disabled by default? Order comment issue

### ISSUE THREAD

**Issue by barryvdh** [paynl/magento2-plugin#188] opened 2023-10-12 15:06 UTC
We ran into issues with https://github.com/boldcommerce/magento2-ordercomments not working with Pay.nl payments. After looking at issues there, it seems to use the validation to save the comment.
Is there a reason the additional validation is not run by default? I've enabled this and it seems to work now, but seems odd behavior by default, or am I missing something? Does is cause compatibility issues?

**Comment by escruickshank** [comment] 2023-10-13 14:58
Hi @barryvd, thank you for your comment! We deemed it "saver" to have this option turned off by default to prevent unwanted behaviour. I am glad to hear it is working for you with the option enabled! 
I will close this issue now as this is built by design. Have a good weekend!

**Closed by escruickshank** 2023-10-13 14:58 UTC
