### ISSUE TITLE
400 Bad Request on purchase

### ISSUE THREAD

**Issue by hocomadvies** [paynl/magento2-plugin#15] opened 2016-11-20 17:53 UTC
Magento 2.1.2

Pay.nl module installed and activated:
api-token and service-id are filled in correct. 

Then when an customer tries to pay an ordered product in the checkout nothing happens. 

the debug of the page shows:

http:/domain.nl/rest/dutch/V1/cards/mine/payment-information 400 Bad request 
Is this the same error as described here: https://github.com/magento/magento2/issues/5902? 

Please provide a solution a.s.p. thanks.

**Comment by andypieters** [comment] 2016-11-21 15:43
Can you first make sure you are using the latest version of the plugin.
And are you using table prefixing? 

If that's the case, then i think it may be the same problem.
The plugin doesn't use its own tables, so i think the problem is not plugin related.

According to the issue, it will be fixed in magento 2.1.3

**Comment by hocomadvies** [comment] 2016-11-21 18:55
I will run an upgrade and see if that make some difference. As far as I know I use the latest version of the plugin. Also I do not use table prefixing. Only thing I can think of could be that I used a module to export products and categories from the old Magento 1.9 into the new Magento 2. 
Which records are used by the module? So I can check if something is wrong there.

Waiting for Magento 2.1.3 is not really an option. We need a pay solution now.

**Comment by 6Ways** [comment] 2016-11-21 19:17
I experienced the exact same error in Magento 2.1.1 installation. After going through the Magento logs, the module was found to have a conflict with another module. Now I can not find the exact reason anymore, this was a few weeks back and I have not kept the logs. It was a database-related error. The Crome dev tools console has not helped me to trace the problem. Magento logs did.

Perhaps it is a good idea to check your Magento logs. And maybe you can disable third-party modules one by one, to see if there is a conflict with another module.

**Comment by hocomadvies** [comment] 2016-11-21 21:26
@6ways Thanks for the suggestion. Any idea which module it was? I did not install so many modules. Since the error line mentioned something "dutch" in it, could it perhaps be caused by a language module installed?

**Comment by hocomadvies** [comment] 2016-11-23 12:57
I un-installed al modules which were  installed and tried over and over again but without any success. The database seems to be ok. Also in the log-files I do not notice any strange things related to this. Any ideas how to troubleshoot this further?

**Comment by akacemy** [comment] 2016-11-23 13:10
Hello,

here is temporary fix for this issue i had the same issue and it was fixed using it:

1 - First please make backup of the database,

2 - Remove database tables prefix for all tables,

3 -  Update table "**sales_sequence_meta**" remove the prefix from column "**sequence_table**",
             the rows on the column "**sequence_table**" should look like this:
                  

```
sequence_order_0
sequence_invoice_0
sequence_creditmemo_0
sequence_shipment_0
sequence_order_1
sequence_invoice_1
sequence_creditmemo_1
sequence_shipment_1
```

4 - update your app/etc/env.php
     `  line 17:  change 'table_prefix' => 'YOURPREFIX_', to 'table_prefix' => '',`
5 - Clear the cache.

and you are done. 

Hope this help as temporary fix till the official.

**Comment by hocomadvies** [comment] 2016-11-23 14:26
No this is not a solution. I went through all these steps before and all these settings were good. I dropped a comment also in https://github.com/magento/magento2/issues/6929 which seems to be related to the problem.

Any other suggestions are welcome!

**Comment by tempo-ruud** [comment] 2016-11-26 17:37
I don't use any prefixes and I also have the same issue. I must say for a payment service provider this is not good support. Payments are crucial for a webshop and waiting for 6 days to get a solution is not how it supposed to be.

**Comment by andypieters** [comment] 2016-11-28 16:19
@hocomadvies 
Can you please try if you have the same error when you choose the standard 'Banktransfer' payment method of magento2?

**Comment by hocomadvies** [comment] 2016-11-29 11:33
@andypieters Unfortunately, yes its throwing the same error! So its not (just) a error thrown by the pay.nl module I guess. In the topic mentioned above which seems to be related are many users having the same problem. Seems to be a Magento2 bug.

**Comment by tempo-ruud** [comment] 2016-11-29 11:34
You meant, Magento2 seems to be a bug @hocomadvies

**Comment by hocomadvies** [comment] 2016-11-29 11:39
Its a complete nightmare. Have never experienced such a dramatic project before. ;)

**Comment by tempo-ruud** [comment] 2016-11-29 11:40
Lets complain more on the magento topic @hocomadvies . Everyone is talking kindly to magento but they don't deserve a kind treatment.

**Comment by tempo-ruud** [comment] 2016-11-30 14:46
@hocomadvies ik heb het probleem aan onze kant gevonden. Bij ons had het te maken dat de mailserver het niet deed en daardoor de order niet door ging. Daar heeft magento een stomme blokkade opzitten zoals het blijkt.

**Comment by hocomadvies** [comment] 2016-11-30 14:58
Good for you you found a solution. 
I did look at the mail-server before and I think its working ok in my system. When a new customer register a mail is send out so I assume it also works when checking out. 
What did you change there? Might be worthwhile looking into again :)

**Comment by tempo-ruud** [comment] 2016-11-30 15:04
Ouch sorry, was to early to report this. It is not working.

Sorry @hocomadvies

**Closed** 2017-01-11 14:50 UTC
